### ISSUE TITLE
MFit::ExecuteError: there are no fittable parameters WHY?

### ISSUE THREAD

**Issue by raypangping** [wojdyr/fityk#16]
code as below:

    load_data(0, vec[0], vec[1], vec[2]);
    execute("set fitting_method=mpfit");
    execute("fit");

but there is exception in **void Fit::fit(int max_eval, const vector<Data*>& datas) update_par_usage(datas);**  

how to add  parameters?

**Comment by wojdyr** [comment]
I'm not sure what you want to do, but a general answer is that
parameters, variables, models, etc. are described in
http://fityk.nieto.pl/model.html

**Comment by raypangping** [comment]
Duplicate of # thank you
