### ISSUE TITLE
Default function indexing

### ISSUE THREAD

**Issue by Fellow-baka** [wojdyr/fityk#21]
Is there a reason why default function names starts with _1 instead _0? It seems like it could be a bit clearer to have consistency in name-index for usual tasks e.g. looking for a specific function in GUI list and performing the operations in CL using its default name.

```
=-> lua print(F:all_functions()[0].name)
_1
```

**Comment by wojdyr** [comment]
In general you can't rely on the functions being in order (for example, after one of the functions is deleted the correspondence between function names and indexes changes). So I don't think that such an initial consistency would be a significant benefit.
