### ISSUE TITLE
Autoconf cannot find boost OpenBSD

### ISSUE THREAD

**Issue by ddkn** [wojdyr/fityk#30]
Hello, 

I am following the INSTALL guide and not an expert with autoconf tools by any means with hopes to make a port for OpenBSD. However, when invoking `./configure` I get the following lines:

~~~
...
checking for sstream... yes
checking boost/math/special_functions/gamma.hpp usability... no
checking boost/math/special_functions/gamma.hpp presence... no
checking for boost/math/special_functions/gamma.hpp... no
configure: error: Boost::Math headers not found. Make sure you have Boost installed.
~~~

However, on the system `/usr/local/include/boost/math/special_functions` exist with the right files. I have tried changing `CFLAGS CPPFLAGS CXXFLAGS` to no avail, I have also tried changing the `AC_CHECK_HEADER` to use `/usr/local/include/boost/math/special_functions/gamma.hpp`

Any help would be greatly appreciated.

**Comment by wojdyr** [comment]
Hi,
try setting CPPFLAGS like this:

    ./configure CPPFLAGS="-I/usr/local/include"
