### ISSUE TITLE
C++17 has dropped support for dynamic exceptions

### ISSUE THREAD

**Issue by badshah400** [wojdyr/fityk#37]
GCC 11 uses the C++17 standard, which has dropped support for [dynamic exceptions](https://en.cppreference.com/w/cpp/language/except_spec), by default. As a result, building fityk on a distro with GCC 11 as the default compiler (such as openSUSE Tumbleweed) causes compilation errors due to throws like these:

https://github.com/wojdyr/fityk/blob/d98158990ae4349a4a27dc3c6ec2800db453b263/fityk/fityk.h#L335

I can simply switch to forcing C++11 or C++14 when compiling, but I thought I'd get an opinion from you. Thanks for the great app.

**Comment by SoapGentoo** [comment]
The correct solution is to remove dynamic exception specifications, [which are considered a mistake in the history of C++](https://herbsutter.com/2007/01/24/questions-about-exception-specifications/).

**Comment by wojdyr** [comment]
Hi @badshah400
I forgot to reply. I'll modernize the code at some point, but I don't know when, unfortunately I don't spend much time maintaining fityk nowadays. Currently, it's still C++98 and should compile up to C++14.
The last release (that was made years ago) also doesn't work well with GTK3. I think I've fixed most of the issues in git. l need to make a new release soon.

**Comment by badshah400** [comment]
Thanks, we enforced `c++14` to fix our package. Looking forward to a new release.
